# Generated by Django 4.1 on 2022-09-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_icon'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
