# Generated by Django 4.1 on 2022-09-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_bug_created_by_alter_bug_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='comment_attachments/'),
        ),
    ]
