# Generated by Django 4.1 on 2022-09-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugresolution',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='team_members',
        ),
    ]
