# Generated by Django 4.1 on 2022-09-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_alter_media_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='acceptance',
            field=models.BooleanField(blank=True, choices=[(True, 'Aceepted'), (False, 'Rejected'), (None, 'Under Review')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='found_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_found_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_team', to='tracker.teams'),
        ),
        migrations.AlterField(
            model_name='bugresolution',
            name='error_function_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_error_function_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
