# Generated by Django 4.1 on 2022-09-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_bugresolution_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastore',
            name='media_type',
            field=models.CharField(default='etc', max_length=20),
        ),
    ]
