# Generated by Django 4.1 on 2022-09-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0004_alter_bug_acceptance_alter_bug_found_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugresolution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
