# Generated by Django 4.1 on 2022-09-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_bugresolution_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='Team_Leader',
            new_name='team_Leader',
        ),
    ]
