# Generated by Django 4.1 on 2022-09-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_team_leader_teams_team_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='team_Leader',
            new_name='team_leader',
        ),
    ]
