# Generated by Django 4.1 on 2022-09-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_media_mediastore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugduplicate',
            name='duplicate_id',
        ),
        migrations.AddField(
            model_name='bugduplicate',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
