# Generated by Django 4.1 on 2022-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_teams_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_media', to='tracker.mediastore'),
        ),
    ]
