# Generated by Django 4.1 on 2022-09-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_bug_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_media', to='tracker.mediastore'),
        ),
        migrations.AlterField(
            model_name='bugresolution',
            name='bug',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_bug', to='tracker.bug'),
            preserve_default=False,
        ),
    ]
