# Generated by Django 4.1 on 2022-09-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_bug_media_alter_bugresolution_bug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messeges',
            name='comment_date',
        ),
        migrations.AddField(
            model_name='messeges',
            name='bug_resolution_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_bug_resolution', to='tracker.bugresolution'),
            preserve_default=False,
        ),
    ]
