# Generated by Django 4.1 on 2022-09-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tracker', '0013_remove_messeges_comment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='media',
        ),
        migrations.RemoveField(
            model_name='messeges',
            name='attachments',
        ),
        migrations.AddField(
            model_name='mediastore',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mediastore',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
