# Generated by Django 4.1 on 2022-09-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_bug_media_remove_messeges_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediastore',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mediastore',
            name='object_id',
        ),
        migrations.AddField(
            model_name='bug',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_attachments', to='tracker.mediastore'),
        ),
        migrations.AddField(
            model_name='messeges',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_attachments', to='tracker.mediastore'),
        ),
        migrations.AlterField(
            model_name='mediastore',
            name='media_file',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
